ImuConfig:
  imu_file_path: "../data/imu/MS1.txt"
  imu_topic: "imu_data"
  frequency: 100
  Transformation_i_c:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation_euler:
      x: 0.0          # roll 
      y: 0.0          # pitch
      z: 0.0          # yaw  
  Transformation_i_l:
    translation:
      x: 1.0
      y: 0.0
      z: 0.0
    rotation_euler:
      x: 0.0          # roll 
      y: 0.0          # pitch
      z: 0.0          # yaw  
  Transformation_i_b:
    translation:
      x: 0.5
      y: 0.5
      z: 0.0
    rotation_euler:
      x: 0.0          # roll 
      y: 0.0          # pitch
      z: 0.0          # yaw  

  LoggerConfig:
    log_file_path: "../log/imu_log.txt"
    enable_console_log: true
    console_log_levels:
      - "FATAL"
      - "ERROR"
      # - "WARN"
      # - "INFO"
      # - "DEBUG"
      # - "ALL"

  TimerConfig:
    time_unit: "ms"

  PreIntegration:
    init_ba:
      x: 0.0
      y: 0.0
      z: 0.0
    init_bg:
      x: 90.0
      y: 0.0
      z: 0.0
    noise_acc: 0.0
    noise_gyr: 0.0